import Foundation

struct Quotes {
    var quote: String
    var author: String
}

var DATA = [
    Quotes(quote: "I’ve learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.", author: "Maya Angelou"),
    Quotes(quote: "Either you run the day, or the day runs you.", author: "Jim Rohn"),
    Quotes(quote: "Whether you think you can or you think you can’t, you’re right.", author: "Henry Ford"),
    Quotes(quote: "The two most important days in your life are the day you are born and the day you find out why.", author: "Mark Twain"),
    Quotes(quote: "Whatever you can do, or dream you can, begin it.  Boldness has genius, power and magic in it.", author: "Johann Wolfgang von Goethe"),
    Quotes(quote: "The best revenge is massive success.", author: "Frank Sinatra"),
    Quotes(quote: "People often say that motivation doesn’t last. Well, neither does bathing.  That’s why we recommend it daily.", author: "Zig Ziglar"),
    Quotes(quote: "Life shrinks or expands in proportion to one’s courage.", author: "Anais Nin"),
    Quotes(quote: "If you hear a voice within you say “you cannot paint,” then by all means paint and that voice will be silenced.", author: "Vincent Van Gogh"),
    Quotes(quote: "There is only one way to avoid criticism: do nothing, say nothing, and be nothing.", author: "Aristotle"),
    Quotes(quote: "Ask and it will be given to you; search, and you will find; knock and the door will be opened for you.", author: "Jesus"),
    Quotes(quote: "The only person you are destined to become is the person you decide to be.", author: "Ralph Waldo Emerson"),
    Quotes(quote: "Go confidently in the direction of your dreams.  Live the life you have imagined.", author: "Henry David Thoreau"),
    Quotes(quote: "When I stand before God at the end of my life, I would hope that I would not have a single bit of talent left and could say, I used everything you gave me.", author: "Erma Bombeck"),
    Quotes(quote: "Few things can help an individual more than to place responsibility on him, and to let him know that you trust him.", author: "Booker T. Washington"),
    Quotes(quote: "Certain things catch your eye, but pursue only those that capture the heart.", author: " Ancient Indian Proverb"),
    Quotes(quote: "Believe you can and you’re halfway there.", author: "Theodore Roosevelt"),
    Quotes(quote: "Everything you’ve ever wanted is on the other side of fear.", author: "George Addair"),
    Quotes(quote: "We can easily forgive a child who is afraid of the dark; the real tragedy of life is when men are afraid of the light.", author: "Plato"),
    Quotes(quote: "Teach thy tongue to say, “I do not know,” and thous shalt progress.", author: "Maimonides"),
    Quotes(quote: "Start where you are. Use what you have.  Do what you can.", author: "Arthur Ashe"),
    Quotes(quote: "When I was 5 years old, my mother always told me that happiness was the key to life.  When I went to school, they asked me what I wanted to be when I grew up.  I wrote down ‘happy’.  They told me I didn’t understand the assignment, and I told them they didn’t understand life.", author: "John Lennon"),
    Quotes(quote: "Fall seven times and stand up eight.", author: "Japanese Proverb"),
    Quotes(quote: "When one door of happiness closes, another opens, but often we look so long at the closed door that we do not see the one that has been opened for us.", author: "Helen Keller"),
    Quotes(quote: "Everything has beauty, but not everyone can see.", author: "Confucius"),
    Quotes(quote: "How wonderful it is that nobody need wait a single moment before starting to improve the world.", author: "Anne Frank"),
    Quotes(quote: "When I let go of what I am, I become what I might be.", author: "Lao Tzu"),
    Quotes(quote: "Life is not measured by the number of breaths we take, but by the moments that take our breath away.", author: "Maya Angelou"),
    Quotes(quote: "Happiness is not something readymade.  It comes from your own actions.", author: "Dalai Lama"),
    Quotes(quote: "If you’re offered a seat on a rocket ship, don’t ask what seat! Just get on.", author: "Sheryl Sandberg"),
    Quotes(quote: "First, have a definite, clear practical ideal; a goal, an objective. Second, have the necessary means to achieve your ends; wisdom, money, materials, and methods. Third, adjust all your means to that end.", author: "Aristotle"),
    Quotes(quote: "If the wind will not serve, take to the oars.", author: "Latin Proverb"),
    Quotes(quote: "You can’t fall if you don’t climb.  But there’s no joy in living your whole life on the ground.", author: "Unknown"),
    Quotes(quote: "We must believe that we are gifted for something, and that this thing, at whatever cost, must be attained.", author: "Marie Curie"),
    Quotes(quote: "Too many of us are not living our dreams because we are living our fears.", author: "Les Brown"),
    Quotes(quote: "Challenges are what make life interesting and overcoming them is what makes life meaningful.", author: "Joshua J. Marine"),
    Quotes(quote: "If you want to lift yourself up, lift up someone else.", author: "Booker T. Washington"),
    Quotes(quote: "I have been impressed with the urgency of doing. Knowing is not enough; we must apply. Being willing is not enough; we must do.", author: "Leonardo da Vinci"),
    Quotes(quote: "Limitations live only in our minds.  But if we use our imaginations, our possibilities become limitless.", author: "Jamie Paolinetti"),
    Quotes(quote: "You take your life in your own hands, and what happens? A terrible thing, no one to blame.", author: "Erica Jong"),
    Quotes(quote: "What’s money? A man is a success if he gets up in the morning and goes to bed at night and in between does what he wants to do.", author: "Bob Dylan"),
    Quotes(quote: "I didn’t fail the test. I just found 100 ways to do it wrong.", author: "Benjamin Franklin"),
    Quotes(quote: "In order to succeed, your desire for success should be greater than your fear of failure.", author: "Bill Cosby"),
    Quotes(quote: "A person who never made a mistake never tried anything new.", author: " Albert Einstein"),
    Quotes(quote: "The person who says it cannot be done should not interrupt the person who is doing it.", author: "Chinese Proverb"),
    Quotes(quote: "There are no traffic jams along the extra mile.", author: "Roger Staubach"),
    Quotes(quote: "It is never too late to be what you might have been.", author: "George Eliot"),
    Quotes(quote: "You become what you believe.", author: "Oprah Winfrey"),
    Quotes(quote: "I would rather die of passion than of boredom.", author: "Vincent van Gogh"),
]
